### PR TITLE
Deploy 2021-1.0

### PR DESCRIPTION
**Pull request by mrakitin**
Addresses tasks in #18.

### CODE REVIEW

**Comment by mrakitin** [comment]
@andrewmkiss, @rrobinyang, this is ready for your review and acceptance testing. Please let me know how it goes. If everything works as expected, I will finish with the rest of the tasks in #18. Thank you.

**Review by andrewmkiss — APPROVED** [review]

**Comment by mrakitin** [comment]
@JunAishima, do you mind having a look to see if I missed anything? Thanks!

**Comment by mrakitin** [comment]
@JunAishima, any objections to merging it? If no, I plan to merge it today.

**Review by JunAishima — APPROVED** [review]

**Comment by mrakitin** [comment]
Thanks Jun. Given we have 2 approvals, I am merging this PR.

**Pull request merged**
