### PR TITLE
Migrate databroker handlers

### PR DESCRIPTION
**Pull request by MikeHart85**
Databroker handlers will be migrated to dedicated repositories as part of April deployment.

Related: https://github.com/bluesky/databroker/issues/533

Handlers will be moved to [area-detector-handlers](https://github.com/bluesky/area-detector-handlers) and [nsls2-detector-handlers](https://github.com/bluesky/nsls2-detector-handlers).

### CODE REVIEW

**Comment by mrakitin** [comment]
Needs rebasing, but it's still needed.

**Comment by mrakitin** [comment]
@MikeHart85, do you mind taking care of it (rebasing, etc.)?

**Comment by MikeHart85** [comment]
Yes, will do.

**Comment by MikeHart85** [comment]
This was too out of date to rebase or merge cleanly. Kept showing conflicts where there didn't appear to be any.

I started a fresh branch and PR (#28) and reapplied changes manually. Changes not substantially different, just moved around between files a lot.

Closing this PR unmerged, as it is obsolete and superseded by the above.

**Pull request closed without merging**
