### PR TITLE
Mnt cleanup

### PR DESCRIPTION
**Pull request by tacaswell**
I was trying to get your profile to run against a simulated beamline and these are the changes (plus some other clean up) I had to make to get the profile to run on my computer.

I think moving the calibration and the extra helper file into the profile is a net good so they get tracked with everything else.

Removing the `sys.path` hacking is extremely good.

### CODE REVIEW

**Comment by mrakitin** [comment]
@tacaswell, thanks! How did you feel that SRX is next in my list -- here https://github.com/NSLS-II/profile-collection-ci/issues/2? 😃

**Comment by mrakitin** [comment]
@andrewmkiss, @tacaswell, a few files are copied from `/nsls2/xf05id1/shared/src/bluesky_scripts/`. Should they be a part of this repo?
https://github.com/NSLS-II-SRX/profile_collection/blob/2288cad4a11ef8d828adc4eab8b3be2eb0b9a4f0/startup/90-usersetup.py#L39-L59

**Comment by tacaswell** [comment]
@mrakitin Probably on including those files.

**Comment by mrakitin** [comment]
Closing as obsolete.

**Pull request closed without merging**
